### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by gaodianzhuo** [madlogos/recharts2#2]
R version 3.3.2  windows 64位

devtools::install_github('madlogos/recharts')
Downloading GitHub repo madlogos/recharts@master
from URL https://api.github.com/repos/madlogos/recharts/zipball/master
Installing recharts
"C:/Program Files/R/R-3.3.2/bin/x64/R" --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/arthur-y470p/AppData/Local/Temp/RtmpUX3koc/devtools2538468263e0/madlogos-recharts-ef72a0a"  \
  --library="C:/Program Files/R/R-3.3.2/library" --install-tests 

'C:\Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
错误: Command failed (1)

**Comment by madlogos** [comment]
请到recharts仓库下提交issue。

您的问题参考[这里](https://github.com/madlogos/recharts/issues/2)
