### ISSUE TITLE
plot stack bar chart: subtype = 'stack' didn't work!

### ISSUE THREAD

**Issue by zenbook** [madlogos/recharts2#6]
hello,
I use reharts to plot a stack bar chart, the R code is below:
echartr(data = duration_distribution, 
        x = pay_date, 
        y = order_num, 
        series = duration_class,
        type = 'vbar',
        subtype = 'stack')

but I get nothing in the Viewer tab on Rstudio:
![image](https://user-images.githubusercontent.com/17475586/28202945-2fbf41b0-68aa-11e7-8714-5e13d6b0358b.png)

Did anyone  meet the same problem before?can anyone give me some help,thanks very much!!

**Comment by madlogos** [comment]
This is not a recharts2 issue. it's a recharts issue. Please go to <https://github.com/madlogos/recharts/issues>

Since bar charts in recharts2 library does not support time x-axis, you should coerce pay_date to characters.

**Comment by madlogos** [comment]
Issue moved to [madlogos/recharts #14](https://github.com/madlogos/recharts/issues/14) via [**ZenHub**](https://www.zenhub.com/)
